= pkl-neovim

:uri-lazy-nvim: https://github.com/folke/lazy.nvim
:uri-lazyvim: https://github.com/LazyVim/LazyVim
:uri-neovim: https://neovim.io
:uri-nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter
:uri-packer-nvim: https://github.com/wbthomason/packer.nvim
:uri-snipmate: https://github.com/garbas/vim-snipmate
:uri-ultisnips: https://github.com/SirVer/ultisnips
:uri-vim-plug: https://github.com/junegunn/vim-plug
:uri-homebrew: https://brew.sh
:uri-pkl-lsp: https://pkl-lang.org/lsp/current/index.html

This repository provides language support for Pkl for {uri-neovim}[neovim].

Supported features:

- Syntax highlighting (via {uri-nvim-treesitter}[nvim-treesitter])
- Code folding (via {uri-nvim-treesitter}[nvim-treesitter])
- Code snippets (via {uri-snipmate}[SnipMate] or {uri-ultisnips}[UltiSnips])
- Go-to definition, code completion, typechecking, quick fixes, and more (via {uri-pkl-lsp}[Pkl Language Server])

== Quick Start

1. <<installation,Install the plugin>> through your favorite plugin manager.
2. Download the latest https://github.com/apple/pkl-lsp/releases[Pkl Language Server] +
   Alternatively, install with homebrew with `brew install pkl-lsp`
3. Configure the LSP start command and Pkl CLI path:
+
[source,lua]
----
vim.g.pkl_neovim = {
  start_command = { "java", "-jar", "/path/to/pkl-lsp.jar" },
  pkl_cli_path = { "/path/to/pkl" }
}
----

[[installation]]
== Installation

=== Requirements

* {uri-neovim}[Neovim] version 0.11 or higher.
* {uri-nvim-treesitter}[nvim-treesitter]
* {uri-pkl-lsp}[Pkl Language Server]
* Java 22 or higher

=== vim-plug setup

Here is a sample `+init.vim+` file using {uri-vim-plug}[vim-plug].
To complete the setup, you will need to run `+:PlugInstall+`, then restart neovim.

[source,vim]
----
call plug#begin()
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'https://github.com/apple/pkl-neovim.git'
call plug#end()

" The below is required for enabling the tree-sitter syntax engine, which is used by pkl-neovim.
lua <<EOF
local hasConfigs, configs = pcall(require, "nvim-treesitter.configs")
if hasConfigs then
  configs.setup {
    ensure_installed = "pkl",
    highlight = {
      enable = true,              -- false will disable the whole extension
    },
    indent = {
      enable = true
    }
  }
end
EOF
----

=== lazy.nvim setup

Here's a sample block to add your {uri-lazy-nvim}[Lazy.nvim] configuration.
To complete the setup, restart neovim after adding this to your setup.

This config is compatible with {uri-lazyvim}[LazyVim].

[source,lua]
----
{
  "apple/pkl-neovim",
  lazy = true,
  ft = "pkl",
  dependencies = {
    {
      "nvim-treesitter/nvim-treesitter",
      build = function(_)
        vim.cmd("TSUpdate")
      end,
    },
    "L3MON4D3/LuaSnip",
  },
  build = function()
    require('pkl-neovim').init()

    -- Set up syntax highlighting.
    vim.cmd("TSInstall! pkl")
  end,
  config = function()
    -- Set up snippets.
    require("luasnip.loaders.from_snipmate").lazy_load()
    
    -- Configure pkl-lsp
    vim.g.pkl_neovim = {
      start_command = { "java", "-jar", "/path/to/pkl-lsp.jar" },
      pkl_cli_path = { "/path/to/pkl" }
    }
  end,
}
----

=== packer.nvim setup

Here is a sample `+init.lua+` file using {uri-packer-nvim}[packer.nvim].
To complete the setup, you will need to run `+:PackerSync+`, then restart neovim.

[source,lua]
----
require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'} -- Treesitter syntax highlighting.
  use {'https://github.com/apple/pkl-neovim', after = "nvim-treesitter", run = ":TSInstall! pkl"} -- Pkl syntax highlighting
end)

-- The below is required for enabling the tree-sitter syntax engine, which is used by pkl-neovim.
-- Set up Treesitter languages.
require'nvim-treesitter.configs'.setup {
  ensure_installed = "all", -- or "pkl" for just this plugin.
  highlight = {
    enable = true,              -- false will disable the whole extension
  },
  indent = {
    enable = true
  }
}
----

=== Troubleshooting

Some troubleshooting tips if the installation isn't working:

* Ensure you are using neovim 0.11 or higher.
* Run `:TSInstall pkl` to manually install the Pkl parser.
* If syntax highlighting doesn't work until you `:edit` the pkl file to reload it, ensure that the `pkl-neovim` plugin is configured to run after the `nvim-treesitter` plugin.

== Configuration

To configure pkl-neovim, set variables on `vim.g.pkl_neovim`.
See `:h vim.g.pkl_neovim` for detailed documentation on all of the available configuration options.

== Project syncing

To analyze project dependencies, the Pkl Language Server needs to sync all the PklProjects within the workspace.

To do this, run the `:Pkl syncProjects` command.
Alternatively, run lua function `require('pkl-neovim').sync_projects()`.
