= Installation

:uri-neovim: https://neovim.io
:uri-nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter
:uri-vim-plug: https://github.com/junegunn/vim-plug
:uri-homebrew: https://brew.sh

This plugin requires {uri-neovim}[Neovim] version 0.11 or higher.

Install {uri-nvim-treesitter}[nvim-treesitter] alongside this plugin using your favorite plugin manager.

Here is a sample `+init.vim+` file using {uri-vim-plug}[vim-plug].
To complete the setup, you will need to run `+:PlugInstall+`, then restart neovim.

[source,vim]
----
call plug#begin()
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'https://github.com/apple/pkl-neovim.git'
call plug#end()

" The below is required for enabling the tree-sitter syntax engine, which is used by pkl-neovim.
lua <<EOF
local hasConfigs, configs = pcall(require, "nvim-treesitter.configs")
if hasConfigs then
  configs.setup {
    ensure_installed = "pkl",
    highlight = {
      enable = true,              -- false will disable the whole extension
    },
    indent = {
      enable = true
    }
  }
end
EOF
----

== Configuration

To configure pkl-neovim, set `vim.g.pkl_neovim`.
See `:h pkl-neovim` for detailed documentation on all of the available configuration options.

=== Setting up Pkl Language Server

pkl-neovim can be enhanced with the https://pkl-lang.org/lsp/current/index.html[Pkl Language Server].

To use, first download the latest LSP release from https://github.com/apple/pkl-lsp/releases[GitHub].

Once downloaded, configure `vim.g.pkl_neovim.start_command`:

[source,lua]
----
vim.g.pkl_neovim = {
  start_command = { "java", "-jar", "path/to/pkl-lsp.jar" }
}
----

The Pkl Language Server currently requires Java 22 or higher to run.

NOTE: macOS and Linux users can also use {uri-homebrew}[Homebrew] to install the language server with `brew install pkl-lsp`. If you do this, the start command can simply be `{ "pkl-lsp" }`.
