= Installation

:uri-neovim: https://neovim.io
:uri-tree-sitter-manager: https://github.com/romus204/tree-sitter-manager.nvim
:uri-vim-plug: https://github.com/junegunn/vim-plug
:uri-homebrew: https://brew.sh

This plugin requires {uri-neovim}[Neovim] version 0.12 or higher. It uses
Neovim's built-in Tree-sitter support.

{uri-tree-sitter-manager}[tree-sitter-manager.nvim] is optional but recommended
for installing the Pkl parser. The example below uses it as a separate plugin,
not as a pkl-neovim dependency.

Here is a sample `+init.vim+` file using {uri-vim-plug}[vim-plug].
To complete the setup, you will need to run `+:PlugInstall+`, then restart neovim.

[source,vim]
----
call plug#begin()
Plug 'romus204/tree-sitter-manager.nvim'
Plug 'https://github.com/apple/pkl-neovim.git'
call plug#end()

lua <<EOF
require("tree-sitter-manager").setup {
  ensure_installed = { "pkl" },
  languages = {
    pkl = {
      install_info = {
        url = "https://github.com/apple/tree-sitter-pkl.git",
        revision = "v0.20.0",
        queries = "queries",
      },
    },
  },
}
EOF
----

== Configuration

To configure pkl-neovim, set `vim.g.pkl_neovim`.
See `:h pkl-neovim` for detailed documentation on all of the available configuration options.

=== Setting up Pkl Language Server

pkl-neovim can be enhanced with the https://pkl-lang.org/lsp/current/index.html[Pkl Language Server].

To use, first download the latest LSP release from https://github.com/apple/pkl-lsp/releases[GitHub].

Once downloaded, configure `vim.g.pkl_neovim.start_command`:

[source,lua]
----
vim.g.pkl_neovim = {
  start_command = { "java", "-jar", "path/to/pkl-lsp.jar" }
}
----

The Pkl Language Server currently requires Java 22 or higher to run.

NOTE: macOS and Linux users can also use {uri-homebrew}[Homebrew] to install the language server with `brew install pkl-lsp`. If you do this, the start command can simply be `{ "pkl-lsp" }`.
